name: secretless-azure-secure-step1
metadata:
  template: secretless-conference-demo

infra:
  path: ./azd

workflows:
  up:
    - azd: provision --location swedencentral

hooks:
  postprovision:
    shell: sh
    run: bash ./apply.sh
