name: secretless-azure-secure-start
metadata:
  template: secretless-conference-demo

infra:
  path: .

workflows:
  up:
    - azd: restore
    - azd: provision --location swedencentral
    - azd: package --all
    - azd: deploy --all

services:
  api:
    project: ../../src/Secretless.AzureSecureDemo.csproj
    host: appservice
    language: dotnet
