name: secretless-azure-secure-final
metadata:
  template: secretless-conference-demo

infra:
  path: ../start

workflows:
  up:
    steps:
      - run: bash ./prepare-deploy.sh

services:
  api:
    project: ../../src/Secretless.AzureSecureDemo.csproj
    host: appservice
    language: dotnet
